### ISSUE TITLE
Find replace puts JSON from related links into another property

### ISSUE THREAD

**Issue by motohead400** [thecogworks/findandreplace#2]
When I use this tool and the term I'm searching for is in a related links link, it puts the JSON of the related links property into another property on the same page that has nothing to do with the related links:

![related links](https://user-images.githubusercontent.com/23037268/32276036-edd87f1a-bee3-11e7-9ea7-61b409c5dc03.PNG)

![json in other property](https://user-images.githubusercontent.com/23037268/32276044-f2816e0a-bee3-11e7-90e1-19fa8f899b72.PNG)

I'm using Umbraco version 7.6.5 assembly: 1.0.6428.37121

**Comment by motohead400** [comment]
This wasn't just a bug from the related links data type, it had to do with the search term being found in two properties on the same page.  I submitted a pull request with the fix.

**Comment by mzajkowski** [comment]
Fixed in #3. #h5yr @motohead400 !
